from typing import List


def get_questoes() -> List[dict]:
    return [
        {'trechoCaracteristico':'É constitucional a vedação de continuidade da percepção de aposentadoria especial','titulo':'APOSENTADORIA ESPECIAL. Necessidade de afastamento das atividades especiais'},
        {'trechoCaracteristico':'791961','titulo':'APOSENTADORIA ESPECIAL. Necessidade de afastamento das atividades especiais'},
        {'trechoCaracteristico':'791.961','titulo':'APOSENTADORIA ESPECIAL. Necessidade de afastamento das atividades especiais'},
        {'trechoCaracteristico':'TEMA 709','titulo':'APOSENTADORIA ESPECIAL. Necessidade de afastamento das atividades especiais'},
        {'trechoCaracteristico':'continuar no exercício de atividade ou operação que o sujeite aos agentes nocivos constantes da relação','titulo':'APOSENTADORIA ESPECIAL. Necessidade de afastamento das atividades especiais'},
        {'trechoCaracteristico':'devem incidir somente sobre as parcelas vencidas até a data da sentença de procedência','titulo':'CONSECTÁRIOS LEGAIS. Honorários advocatícios sucumbenciais'},
        {'trechoCaracteristico':'não incidem sobre as prestações vencidas após a sentença','titulo':'CONSECTÁRIOS LEGAIS. Honorários advocatícios sucumbenciais'},
        {'trechoCaracteristico':'independentemente de sua natureza e para fins de atualização monetária, de remuneração do capital e de compensação da mora, inclusive do precatório, haverá a incidência, uma única vez, até o efetivo pagamento','titulo':'CONSECTÁRIOS LEGAIS. Juros e correção monetária'},
        {'trechoCaracteristico':'TEMA 810','titulo':'CONSECTÁRIOS LEGAIS. Juros e correção monetária'},
        {'trechoCaracteristico':'na parte em que disciplina a atualização monetária das condenações impostas à Fazenda Pública segundo a remuneração oficial da caderneta de poupança','titulo':'CONSECTÁRIOS LEGAIS. Juros e correção monetária'},
        {'trechoCaracteristico':'o período de efetiva atividade laborativa somente passou a integrar o patrimônio jurídico da parte autora após a integral quitação da indenização do período','titulo':'DIREITO AO BENEFÍCIO. Efeito constitutivo das indenizações após a EC 103/2019'},
        {'trechoCaracteristico':'ele só passa a existir a partir do momento em que é efetuado e surte efeitos apenas para contagens futuras','titulo':'DIREITO AO BENEFÍCIO. Efeito constitutivo das indenizações após a EC 103/2020'},
        {'trechoCaracteristico':'não se podem conferir efeitos anteriores à quitação integral da indenização','titulo':'DIREITO AO BENEFÍCIO. Efeito constitutivo das indenizações após a EC 103/2021'},
        {'trechoCaracteristico':'emissão de guias para pagamento','titulo':'DIREITO AO BENEFÍCIO. Emissão de guias de pagamento'},
        {'trechoCaracteristico':'requer a emissão','titulo':'DIREITO AO BENEFÍCIO. Emissão de guias de pagamento'},
        {'trechoCaracteristico':'seja possibilitada a emissão de guia','titulo':'DIREITO AO BENEFÍCIO. Emissão de guias de pagamento'},
        {'trechoCaracteristico':'erro na contagem','titulo':'DIREITO AO BENEFÍCIO. Erro de contagem do tempo de contribuição'},
        {'trechoCaracteristico':'erro material na contagem','titulo':'DIREITO AO BENEFÍCIO. Erro de contagem do tempo de contribuição'},
        {'trechoCaracteristico':'Tema 995','titulo':'DIREITO AO BENEFÍCIO. Reafirmação da DER'},
        {'trechoCaracteristico':'mesmo que isso se dê no interstício entre o ajuizamento da ação e a entrega da prestação jurisdicional nas instâncias ordinárias','titulo':'DIREITO AO BENEFÍCIO. Reafirmação da DER'},
        {'trechoCaracteristico':'requer reafirmação da DER','titulo':'DIREITO AO BENEFÍCIO. Reafirmação da DER'},
        {'trechoCaracteristico':'requer a reafirmação da DER','titulo':'DIREITO AO BENEFÍCIO. Reafirmação da DER'},
        {'trechoCaracteristico':'seja reafirmada a DER','titulo':'DIREITO AO BENEFÍCIO. Reafirmação da DER'},
        {'trechoCaracteristico':'início dos efeitos financeiros','titulo':'DIREITO AO BENEFÍCIO. Termo inicial dos efeitos financeiros'},
        {'trechoCaracteristico':'termo inicial dos efeitos financeiros','titulo':'DIREITO AO BENEFÍCIO. Termo inicial dos efeitos financeiros'},
        {'trechoCaracteristico':'efeitos financeiros da concessão do benefício','titulo':'DIREITO AO BENEFÍCIO. Termo inicial dos efeitos financeiros'},
        {'trechoCaracteristico':'efeitos financeiros do benefício','titulo':'DIREITO AO BENEFÍCIO. Termo inicial dos efeitos financeiros'},
        {'trechoCaracteristico':'TEMA 1124','titulo':'DIREITO AO BENEFÍCIO. Termo inicial dos efeitos financeiros'},
        {'trechoCaracteristico':'requer que o termo inicial dos efeitos financeiros seja fixado na data da citação','titulo':'DIREITO AO BENEFÍCIO. Termo inicial dos efeitos financeiros'},
        {'trechoCaracteristico':'indeferimento da produção de perícia médica','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de perícia médica'},
        {'trechoCaracteristico':'indeferimento da realização de perícia médica','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de perícia médica'},
        {'trechoCaracteristico':'indeferida a realização de perícia médica','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de perícia médica'},
        {'trechoCaracteristico':'indeferida a perícia médica','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de perícia médica'},
        {'trechoCaracteristico':'indeferimento da produção de prova pericial','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de prova pericial'},
        {'trechoCaracteristico':'indeferimento da realização de perícia','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de prova pericial'},
        {'trechoCaracteristico':'indeferida a produção de prova pericial','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de prova pericial'},
        {'trechoCaracteristico':'indeferida a realização de perícia','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de prova pericial'},
        {'trechoCaracteristico':'indeferida a perícia','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de prova pericial'},
        {'trechoCaracteristico':'indeferimento da produção de prova testemunhal','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de prova testemunhal'},
        {'trechoCaracteristico':'indeferimento da oitiva','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de prova testemunhal'},
        {'trechoCaracteristico':'indeferida a produção de prova testemunhal','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de prova testemunhal'},
        {'trechoCaracteristico':'indeferida a oitiva','titulo':'QUESTÃO PROCESSUAL. Cerceamento de defesa por negativa de prova testemunhal'},
        {'trechoCaracteristico':'a lei não prejudicará o direito adquirido, o ato jurídico perfeito e a coisa julgada','titulo':'QUESTÃO PROCESSUAL. Coisa julgada'},
        {'trechoCaracteristico':'O direito da Previdência Social de anular os atos administrativos de que decorram efeitos favoráveis para os seus beneficiários decai em dez anos','titulo':'QUESTÃO PROCESSUAL. Decadência para a administração'},
        {'trechoCaracteristico':'art. 103-A','titulo':'QUESTÃO PROCESSUAL. Decadência para a administração'},
        {'trechoCaracteristico':'O prazo de decadência do direito ou da ação do segurado','titulo':'QUESTÃO PROCESSUAL. Decadência para o segurado'},
        {'trechoCaracteristico':'parte ilegítima','titulo':'QUESTÃO PROCESSUAL. Ilegitimidade passiva'},
        {'trechoCaracteristico':'ilegitimidade passiva','titulo':'QUESTÃO PROCESSUAL. Ilegitimidade passiva'},
        {'trechoCaracteristico':'do interesse de agir','titulo':'QUESTÃO PROCESSUAL. Interesse de agir'},
        {'trechoCaracteristico':'ausência de interesse de agir','titulo':'QUESTÃO PROCESSUAL. Interesse de agir'},
        {'trechoCaracteristico':'ausência de interesse processual','titulo':'QUESTÃO PROCESSUAL. Interesse de agir'},
        {'trechoCaracteristico':'A pessoa natural ou jurídica, brasileira ou estrangeira, com insuficiência de recursos para pagar as custas, as despesas processuais e os honorários advocatícios tem direito à gratuidade da justiça, na forma da lei','titulo':'QUESTÃO PROCESSUAL. Justiça gratuita'},
        {'trechoCaracteristico':'concessão da justiça gratuita','titulo':'QUESTÃO PROCESSUAL. Justiça gratuita'},
        {'trechoCaracteristico':'concessão da gratuidade','titulo':'QUESTÃO PROCESSUAL. Justiça gratuita'},
        {'trechoCaracteristico':'concessão da assistência judiciária','titulo':'QUESTÃO PROCESSUAL. Justiça gratuita'},
        {'trechoCaracteristico':'Prescreve em cinco anos, a contar da data em que deveriam ter sido pagas, toda e qualquer ação para haver prestações vencidas ou quaisquer restituições ou diferenças devidas pela Previdência Social','titulo':'QUESTÃO PROCESSUAL. Prescrição'},
        {'trechoCaracteristico':'estão prescritas','titulo':'QUESTÃO PROCESSUAL. Prescrição'},
        {'trechoCaracteristico':'eficaz passou a afastar a especialidade das atividades laborais posteriores','titulo':'TEMPO ESPECIAL. Fornecimento de EPI eficaz'},
        {'trechoCaracteristico':'com a comprovação de diminuição ou neutralização da exposição ao agente nocivo','titulo':'TEMPO ESPECIAL. Fornecimento de EPI eficaz'},
        {'trechoCaracteristico':'dentre elas a informação sobre a eficácia do EPI','titulo':'TEMPO ESPECIAL. Fornecimento de EPI eficaz'},
        {'trechoCaracteristico':'nos casos em que o segurado impugna a eficácia do EPI','titulo':'TEMPO ESPECIAL. Fornecimento de EPI eficaz'},
        {'trechoCaracteristico':'depende da sua identificação e de eventual ultrapassagem de limite de tolerância','titulo':'TEMPO ESPECIAL. Necessidade de análise quantitativa para agentes químicos'},
        {'trechoCaracteristico':'que exigem comprovação de uma concentração mínima','titulo':'TEMPO ESPECIAL. Necessidade de análise quantitativa para agentes químicos'},
        {'trechoCaracteristico':'não pode ser analisada genericamente, uma vez que referidos agentes químicos possuem propriedades','titulo':'TEMPO ESPECIAL. Necessidade de análise quantitativa para agentes químicos'},
        {'trechoCaracteristico':'devem ser respeitadas as normas e metodologias vigentes à época da realização da avaliação técnica','titulo':'TEMPO ESPECIAL. Metodologia de aferição do ruído'},
        {'trechoCaracteristico':'a metodologia utilizada para aferição do ruído nos períodos especificados no quadro supra não respeitou a legislação vigente à época','titulo':'TEMPO ESPECIAL. Metodologia de aferição do ruído'},
        {'trechoCaracteristico':'NHO 01 da FUNDACENTRO','titulo':'TEMPO ESPECIAL. Metodologia de aferição do ruído'},
        {'trechoCaracteristico':'a autorização constitucional não é para o reconhecimento da especialidade nos casos em que existe mero risco de acidente','titulo':'TEMPO ESPECIAL. Perigo não enseja especialidade'},
        {'trechoCaracteristico':'não é possível o enquadramento de atividade como especial no RGPS com base em agente perigoso','titulo':'TEMPO ESPECIAL. Perigo não enseja especialidade'},
        {'trechoCaracteristico':'o enquadramento deve se pautar pelo exercício de atividade relacionada a certos grupos profissionais','titulo':'TEMPO ESPECIAL. Perigo não enseja especialidade'},
        {'trechoCaracteristico':'e não é o risco de contaminação que justifica o direito de contagem privilegiada','titulo':'TEMPO ESPECIAL. Permanência da exposição para agentes biológicos'},
        {'trechoCaracteristico':'o contato com agentes biológicos se dá apenas de forma indireta','titulo':'TEMPO ESPECIAL. Permanência da exposição para agentes biológicos'},
        {'trechoCaracteristico':'risco ocupacional deve ser indissociável da produção','titulo':'TEMPO ESPECIAL. Permanência da exposição para agentes biológicos'},
        {'trechoCaracteristico':'deve ser superior ao da população em geral','titulo':'TEMPO ESPECIAL. Permanência da exposição para agentes biológicos'},
        {'trechoCaracteristico':'FUNDACENTRO para aferição da presença do agente biológico','titulo':'TEMPO ESPECIAL. Permanência da exposição para agentes biológicos'}
    ]